### PR TITLE
Update Anicord.theme.css

### PR DESCRIPTION
**Pull request by bz52333**
Can I change https://raw.githubusercontent.com/sang765/Anicord-Theme/main/assets/themeimage.png to my own picture?

### CODE REVIEW

**Comment by sang765** [comment]
Hello, if you want to replace the image in this theme, you can absolutely upload your image to imgur and then replace the image url and it will change. The photo I'm using in this theme is the best I can find at the moment. Thank you.
image

**Comment by bz52333** [comment]
Sorry, I tried, but nothing happened.
I wonder that if you can help me to solve this problem to modify the code
for me ><
So I try to use the IMGUR what you just told me, and the link is
https://imgur.com/a/8LGpMcZ
How can I insert and change to the right code? I will really appreciate
your help in resolving the problem.

HaTienSang ***@***.***> 於 2024年5月6日 週一 下午8:38寫道：

**Comment by sang765** [comment]
Hello @bz52333, if you want use imgur image link you can right click to image and click `Open image in new tab` and copy `i.imgur` image link and changed that in your theme file
image

**Comment by bz52333** [comment]
O M G... It's work!!! Thank you so much for teaching me this, I'm really
appreciate it, And I really love your design, thank you so much!
Now I can use my favorite pic in my Discord, thank you ^^

HaTienSang ***@***.***> 於 2024年5月6日 週一 下午9:00寫道：

**Pull request closed without merging**
